### ISSUE TITLE
Extend data privacy for Workflow

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#14]
Hey,

in my opinion its not that great that everyone with access to this or forked repository can see the mail-adress that are used for running the script.

Would it be possible to delete this line for Workflow use?

im talking about the headline which is displayed when the Script starts "* * * * * * *email* * * * * * * "

**Comment by MehdiRtal** [comment]
Yes I totally get that but how would u be able to indicate the account without the headline?

**Comment by MehdiRtal** [comment]
But I believe adding a "--privacy" switch would be better.

**Comment by DerMuffin** [comment]
That would be awesome!

Mehdi Rtal ***@***.***> schrieb am Mi., 21. Sept. 2022, 22:34:

**Comment by MehdiRtal** [comment]
I've just added the feature, you can now edit the "deploy" workflow and add "--privacy".
