### ISSUE TITLE
How does th proxy feature work

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#19]
Hey,

see that you add a new --proxies argument in you last commit. How to use it actually?

Do i need create a new secret where i put in all proxy servers? Or just add --proxies in the end of the script?

Thanks in advanced

**Comment by MehdiRtal** [comment]
Well, both things will work, if you create secret you might aswell just reference it in the deploy workflow, else you can just put all the proxies in the following format: ip1:port1 ip2:port2

**Comment by DerMuffin** [comment]
Dont know if anyone use this feature. But if i try to add a proxie, i just cant get it to work.

There a a few things im not sure about:

1.) Which kind of proxies are supported? http(s), sock etc.
2.) How to fill --proxies? 
Like this: 
--proxies https://123.456.7.8:8080 https://876.543.2.1:8080 

or 

Just with IP and Port:
--proxies 123.456.7.8:8080 https://876.543.2.1:8080

All try all things i can imagine. All i got is this "UnboundLocalError: local variable 'browser' referenced before assignment" error which is present in some other errors.

Maybe some of you using this feature and know how it works.

Thanks!

**Comment by gdrhzrd6e** [comment]
--proxies 123.456.7.8:8080 876.543.2.1:8080 thats correct
