### ISSUE TITLE
Deprecation warning "set-output" Github Workflow

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#21]
Hey,

this one pop-up too:

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by MehdiRtal** [comment]
I have updated all the actions. It shouldn't cause a problem in the future now.
