### ISSUE TITLE
this isn't an issue but would cookie loading work with GitHub actions

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#26]
sometimes it bypasses the account suspension prompt which you can unlock when you need to
so i was able to get 6 accounts up to 6000 points before the auth cookies broke or expired

**Comment by MehdiRtal** [comment]
Could you please clarify more?

**Comment by gdrhzrd6e** [comment]
Microsoft doesn't stop you using ms rewards when you have account phone lock

**Comment by gdrhzrd6e** [comment]
which removes need for this feature Detect locked accounts.

**Comment by gdrhzrd6e** [comment]
if loading cookies is added

**Comment by MehdiRtal** [comment]
I can add that.

**Comment by MehdiRtal** [comment]
I will soon provide you with an ETA.
