### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#27]
when this pops up it doesn't get removed and script times out means sometimes you manually have to watch the script

https://lens.google.com/search?p=AU55jv13xx8bkQuzwFm21CYQhwRRLnM-1K6Br-WMo1k30mJC3c36bsq-ZtHwl0RPg_gEyNAtZBOFiSLGinsUcn72ZOoOHnvLJpMMMjYEvNIiXISpZfr00dGSoumxQyry2GumQrrNRarkyZNpi1SY7xYa6998sE1l_Zarqeah60RCdKo3b3WU972nXm3pNBfiMSF65SPI-Fwz_g8xYtSvEFm0h3SXgUtt5JdUZe4g7Nm5Pu694VmfJMAVS_aEN_bFk9QElNFwV7287c6AU5eSc3sVIL1da08kFdstOeiHJ59TWuYy_qVE2Se2dKDungtoqfvkUl4uJyNCEXV4sPktZfDJn1OQ&ep=gsbubb&hl=en-AU#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKREUzTVRobE1HWTVMV1k0WWpndE5HVTNNaTA1TUdVeExXUmxZelJqWkRGaFpXSTRaUklmVFhwdmFHSTVhMGs1U2xsVldVeHVaVFo2U1ROWFNFNHhaREJpYlZGQ1p3PT0iXQ==

<div id="bnp.nid.63713" data-viewname="MobileOpalRichTOP" data-vertical="serp" style="display: block;" data-bm="12"><div class="FlexLayout"><div id="bnp_rich_div" data-scrollhide="false" data-animate="false" data-priority="2" style="background: rgb(57, 85, 163);"><div class="content_with_title"><div class="bnp_bop_icon"><img class="bnp_icon rms_img" id="bnp_icon" role="presentation" data-priority="2" src="/rp/hvUJK8j9Cnex-2F2pxm5HAFXHXI.png" data-bm="10"></div><div class="content_container"><h5 class="title" id="title" style="color: rgb(255, 255, 255);">Get the free Bing app designed for your smartphone.</h5><a id="bnp_bop_cta" data-applink="0" href="https://aka.ms/Bing_Mobile_SetDefault_Control2" h="ID=Bnp,5007.1" style="background: rgb(255, 255, 255);"><span id="bnp_bop_cta_link_text" style="color: rgb(57, 85, 163);">Install it now</span></a></div><div class="header"><div class="bnp_bop_close_icon" id="bnp_bop_close_icon"><img class="icon rms_img" alt="close" data-priority="2" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAgMAAABinRfyAAAADFBMVEX///+qqqqqqqqqqqpHkvemAAAAA3RSTlMAzN1lW/L1AAAAP0lEQVQIHTWMwQkAIAwDD78u4AD+u6G4mHSVjtFXEQN+AiGXY8BkwcF3Kyx60tOCVr7BC7D88aoGIYJ1k+CpLgj9GfvtZs+PAAAAAElFTkSuQmCC" data-bm="11"></div></div></div></div></div></div>

**Comment by gdrhzrd6e** [comment]
i included html but it didn't come out as plain text

**Comment by gdrhzrd6e** [comment]
with coffee donations am i literally buying you coffee or giving money?

**Comment by gdrhzrd6e** [comment]
if you think you can somehow use it im happy giving 30 Australian Harvey Norman egiftcard?
cause there isn't paypal option for donating

**Comment by DerMuffin** [comment]
Correct. Its mostly appear when on mobile search page. But also when the script try to run desktop searches.

When i close this banner on my machine (not headless mode) or open that menu with the three bars in the upper right corner by myself it just works fine.

**Comment by gdrhzrd6e** [comment]
maybe you could get it to click on the element by pixel instead of id?

**Comment by gdrhzrd6e** [comment]
not sure if pixels change depending on page size

**Comment by gdrhzrd6e** [comment]
also for the GitHub actions enable the ability to safe logs to external server and then fetch them when needed

**Comment by gdrhzrd6e** [comment]
or for the bot version you could make a image macro

**Comment by gdrhzrd6e** [comment]
the popup appears at the bottom now instead of the top sometimes?

**Comment by DerMuffin** [comment]
> the popup appears at the bottom now instead of the top sometimes?

Thats a different one. No need to remove it. It doesnt block anything.

**Comment by DerMuffin** [comment]
> not sure if pixels change depending on page size

Bad Idea in my opinion. If the banner moves a second time it also does not work. Button ID works until they changed name for the button.

Its great how it is right now. We just need to update that mentioned part of the code

**Comment by DerMuffin** [comment]
Maybe this help:

https://github.com/farshadz1997/Microsoft-Rewards-bot/commit/e703acd7d7c8b5713989823f02c96721be6f4172

**Comment by gdrhzrd6e** [comment]
i'll run through another set of accounts till it comes up again then look at it

**Comment by gdrhzrd6e** [comment]
the annoying one hasn't popped up only the other version


https://lens.google.com/search?p=AU55jv2CgDfOG96UeX-yrxEv1ypJehI2oKrHYEBmG_3OAVSkoVnLP1G__y-tiC3smVN_Ninwi3NCB1kToqtWHswTSAZCn2At-7Wz5MSypLfa0pNH0a3VhQmWuq9acPlucX38ZK4yg3PbUKh5stht7nQM0Uu73hu3sdyRnUI1xWypZhhf-r4sBcrNNMmjuFVrJeLpL_gsS6iAcg-HruXn2YVj4gNNcdhIwTPs5H2KLtVgDTv-XxYa_TNoWgavE5kM1JAtPq4XtdZYePaP3iD6xrY_CYKKSqqxY2gjbbBC2zmtTYQlybmyjShM0rbsuRkePay3MeetoPeei2g%3D&ep=gsbubb&hl=en#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR00wTXpBMU1UYzJMVEpqTkRBdE5ESm1ZeTFoTmpBM0xXVTVaalJrTXpJek9UTXpNaElmTkROdE1FNHlNazAwYW5kalJVWkRjWGQ0VEhKTVVEYzJjazluTjFGU1p3PT0iXQ==

**Comment by gdrhzrd6e** [comment]
somehow this makes page repeatedly refresh


https://lens.google.com/search?ep=gsbubb&hl=en&p=AU55jv2A2Ckil9X2Etyh0Bpv9onbsYFY84A7DYMT-hBDR0UNiv200rCRagzqXkza2EwrQ8Isq-d2Oo38PANX0RnFr8TnbuqVeUjU2wMtdh8eC0hcB66w158PnitdlRJmGE6cOAVB47CbmCcfAJWAKrF2p4saAmDJu7yF9stIaR2GNq0tp48BbHWiAQRkepFeQ9yJn38ico0zcFCz_f9jhRz9chiHMzT-uL9lMttxQmUa5u099wCP-ab2ViLujiBTlTxKFrUbMuVLvLKAx8cV7ICXhyoAsVXLpUDtSoLsmGer8T2XAcnKstmhotZXYWqQ3lLodOjB7rqsTfqm#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKREprTXprM1ptUTRMVGxsWW1ZdE5EVmxOQzFoTkRnMUxURmhOVEU1TlRsa09UaGtPUklmWXpobFZETk1MWEYyU1c5aVJVWkRjWGQ0VEhKTVVEVTJTbGxWT0ZGU1p3PT0iLG51bGwsbnVsbCxudWxsXQ==

**Comment by gdrhzrd6e** [comment]
i know this has nothing to do with this issue but you can get bonus 250 points if you do some cookie editing😁

**Comment by gdrhzrd6e** [comment]
i found this ages ago but wanted to see if i could somehow trick into giving more but Bing trial is limited to 250

**Comment by gdrhzrd6e** [comment]
if it resets back to 200 reapply and go straight to bing.com without redirecting page cause it resets whenever you search

**Comment by gdrhzrd6e** [comment]
reloading page i mean

**Comment by gdrhzrd6e** [comment]
MehdiRtal this isn't big need but argument for triggering shutdown when bot finishes might be useful

**Comment by gdrhzrd6e** [comment]
> Correct. Its mostly appear when on mobile search page. But also when the script try to run desktop searches.
> 
> When i close this banner on my machine (not headless mode) or open that menu with the three bars in the upper right corner by myself it just works fine.
> 
> EDIT:
> 
> Double Check it on my Phone. As long this pop-up is active, you cant access the account setting with the three bars. Refresh of the site doesnt remove the pop-up. If its displayed ones, its stays there until you close it.
> 
> EDIT2:
> 
> if isMobile: # close bing app banner if isElementExists(browser, By.ID, 'bnp_rich_div'): browser.find_element(By.XPATH, '//*[@id="bnp_bop_close_icon"]/img').click()
> 
> Maybe they change name of this button. (Line 246 and ongoing). Dont know how to get Button ID.

**Comment by gdrhzrd6e** [comment]
that was

**Comment by gdrhzrd6e** [comment]
@DerMuffin are you just saying id and actually meaning class?

**Comment by gdrhzrd6e** [comment]
browser.find_element(By.XPATH, '//*[@id="bnp_bop_close_icon"]/img').click()
can you just change the id part of this to class without issues?

**Comment by DerMuffin** [comment]
@gdrhzrd6e 

Not sure. Im not into python or anything related. What i know is, that the "Button" to click is somewhere defined and if this reference is changed, the script cant click this button anymore

**Comment by DerMuffin** [comment]
> MehdiRtal this isn't big need but argument for triggering shutdown when bot finishes might be useful

That would be great. On my Machine i just delete that part of the code where it ask to "press any Key" and the machine shutdown after the script is finish (with schedule task)

**Comment by MehdiRtal** [comment]
@gdrhzrd6e could you contact me on discord Sackuro#5802
