### ISSUE TITLE
add in the readme...

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#28]
if you wanna get 250 points before you even sign up install any cookie editor
https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm?hl=en this one good
find cookie value _RwBf change current trial points to 250 don't search otherwise it resets to 200 go straight to bing.com then create account and you'll find that you've instantly gotten all trial points and 50 more that you don't usually get means level 2 on first day without even using vpn glitch

heaps of people must have found this before me if not😢 im sad for them

**Comment by gdrhzrd6e** [comment]
if no idea what im talking about just copy and paste this in rwbf thing while on bing.com



ilt=4&ihpd=2&ispd=2&rc=250&rb=0&gb=0&rg=200&pc=5&mtu=0&rbb=0&g=0&cid=&clo=0&v=4&l=2022-10-26T07:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&o=2&p=&c=&t=0&s=0001-01-01T00:00:00.0000000+00:00&ts=2022-10-26T10:46:00.1722130+00:00&rwred=0

**Comment by gdrhzrd6e** [comment]
also has anyone heard of the outlook.com glitch where you change the from address to the email you want save it reload page
spam trying to send it it won't allow you cause its not your email then you change it back to yours and it sends it still in the email you want🙂  they patched this even though i never told anyone about it so have any of you worked this one out


it still works perfectly sending emails from outlook to gmail just not outlook to outlook
this is purely for my own info on if anyone else has known about this?

**Comment by gdrhzrd6e** [comment]
also xbox gamepass ultimate never has to cost more than a dollar buy it wait 10-20 days or right till a day before expire(haven't tried this) cancel it and you you should at least for 10 days be able to buy it again for 94% off  12 dollars per year

**Comment by gdrhzrd6e** [comment]
and if for some reason you play this trash game but wanna fly a mining barge but only pay for sub once to do so
https://www.eveonline.com/
get it all and never dock up to a station again

**Comment by gdrhzrd6e** [comment]
i live in South Australia so zzzzZZZZzzzz

**Comment by Axel3026** [comment]
![image](https://user-images.githubusercontent.com/87623383/198015520-47488478-620a-4fb9-b7e8-69af4df03988.png)
I found this bug, which was only activated in one account, I am not from the USA, and I don't know how to replicate this error.

**Comment by gdrhzrd6e** [comment]
what exactly is the error no need to replicate im not from usa either

**Comment by gdrhzrd6e** [comment]
or is it that its showing stuff from the usa and your not in the usa?

**Comment by Axel3026** [comment]
yo, uso una vpn, y nose si recargue mucho la pagina o algo random que se me modificaron esos numeros y hasta el dia de hoy estoy ganando 150 en vez de 20

**Comment by gdrhzrd6e** [comment]
sometimes if you go into microsoft rewards then vpn to unsupported country not sure how but it still lets you in which is weird error. but are you sure that you haven't had vpn on constantly this whole time?

**Comment by gdrhzrd6e** [comment]
the thing at the top is a bonus before even creating an account thats its purpose

**Comment by gdrhzrd6e** [comment]
its very possible Microsoft rewards happened to get changed to be the same for everyone recently

**Comment by gdrhzrd6e** [comment]
not sure how this happened but now i understand what you mean

**Comment by gdrhzrd6e** [comment]
no need to be sorry if your using google translate

**Comment by gdrhzrd6e** [comment]
do you keep the accounts logged in?

**Comment by Axel3026** [comment]
Do you have a discord?, and if I keep everything logged in, I think he tries to unlog me and even so the account continues with those 150

**Comment by gdrhzrd6e** [comment]
ThePhishermanman#6479
