### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by DimaRazb** [MehdiRtal/MicrosoftRewardsBot#29]
Not sure if this is related to #27 , but here is the log I see after deploying it in GitHub Actions:

Run python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
sh: 1: color: not found

[LOGS] "logs.txt" file not found.
[LOGS] "logs.txt" created.

[WDM] - Downloading:   0%|          | 0.00/6.35M [00:00<?, ?B/s]
[WDM] - Downloading:   4%|▍         | 272k/6.35M [00:00<00:02, 2.76MB/s]
[WDM] - Downloading:  52%|█████▏    | 3.29M/6.35M [00:00<00:00, 19.7MB/s]
[WDM] - Downloading: 100%|██████████| 6.35M/6.35M [00:00<00:00, 29.0MB/s]
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 3756 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
[DAILY SET] Completed the Daily Set successfully !
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/30
[BING] 2/30
[BING] 3/30
[BING] 4/30
[BING] 5/30
[BING] 6/30
[BING] 7/30
[BING] 8/30
[BING] 9/30
[BING] 10/30
[BING] [11](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:12)/30
[BING] [12](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:13)/30
[BING] [13](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:14)/30
[BING] [14](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:15)/30
[BING] [15](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:16)/30
[BING] [16](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:17)/30
[BING] [17](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:18)/30
[BING] [18](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:19)/30
[BING] [19](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:20)/30
[BING] [20](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:21)/30
[BING] [21](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:22)/30
[BING] [22](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:23)/30
[BING] [23](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:24)/30
[BING] [24](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:25)/30
[BING] [25](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:26)/30
[BING] [26](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:27)/30
[BING] [27](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:28)/30
[BING] [28](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:29)/30
[BING] [29](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:30)/[30](https://github.com/D/MicrosoftRewardsBot/actions/runs/3325071904/jobs/5497369023#step:6:31)
[BING] 30/30
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...

[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.

**Comment by gdrhzrd6e** [comment]
is this on your pc or github actions?

**Comment by DerMuffin** [comment]
@DimaRazb 
Could be multiple issues.

Check if you can login into your accounts. This message also appear when the Account got temporary locked out.

And yes, could be related to the Issue #27 .

Did you try run it manually? Sometimes its just github and something is messed up.

**Comment by DimaRazb** [comment]
It works manually fine, sorry I forgot to mention it, the account is not locked out.
Also- mobile searches do not work for some reason, so that's why I thought it could be related to the issue.

**Comment by DerMuffin** [comment]
Yeah, mobile and sometimes Desktop search too. We need to wait until it get fixed.
