### ISSUE TITLE
exit code 1 (chromedriver crash)

### ISSUE THREAD

**Issue by dystoqia** [MehdiRtal/MicrosoftRewardsBot#32]
Traceback (most recent call last):

```
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 1204, in farmer
    browser = browserSetup(False, PC_USER_AGENT, random.choice(ARGS.proxies) if ARGS.proxies else None)
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 77, in browserSetup
    chrome_browser_obj = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55fe11bc32c3 <unknown>
#1 0x55fe119cc83a <unknown>
#2 0x55fe119f2543 <unknown>
#3 0x55fe119ed546 <unknown>
#4 0x55fe11a2bde6 <unknown>
#5 0x55fe11a2b74f <unknown>
#6 0x55fe11a23d63 <unknown>
#7 0x55fe119f87e3 <unknown>
#8 0x55fe119f9a21 <unknown>
#9 0x55fe11c1118e <unknown>
#10 0x55fe11c14622 <unknown>
#11 0x55fe11bf7aae <unknown>
#12 0x55fe11c152a3 <unknown>
#13 0x55fe11bebecf <unknown>
#14 0x55fe11c35588 <unknown>
#15 0x55fe11c35706 <unknown>
#16 0x55fe11c4f8b2 <unknown>
#17 0x7f866938a609 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 1319, in <module>
    main()
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 1309, in main
    farmer()
  File "/home/runner/work/ms/ms/MicrosoftRewardsBot.py", line 1272, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
Error: Process completed with exit code 1.
```

**Comment by MehdiRtal** [comment]
Is it reproducible?

**Comment by nigh95ms** [comment]
If no one else is having the same problem then no, I even updated the repo and it still didnt work (same error).

I'm going to fork it again and see if it works or not

**Comment by DerMuffin** [comment]
Thats a know issue when running it on Linux without GUI.

Do you use the parameter --headless ?

**Comment by dystoqia** [comment]
No, I don't, but I'll try. Thanks!

**Comment by dystoqia** [comment]
How do I use headless on Github Actions?

**Comment by DerMuffin** [comment]
> How do I use headless on Github Actions?

Should be on by default. Check your workfile for the "deploy" action

![image](https://user-images.githubusercontent.com/53898156/200247093-804006f0-36cf-474c-b405-df5ef8b93e75.png)
![image](https://user-images.githubusercontent.com/53898156/200247206-fe4515b7-c1aa-4b65-919c-79ca18498ca7.png)

**Comment by dystoqia** [comment]
Thanks

**Comment by dystoqia** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/80724583/200448075-bcb192c2-28a5-4a6b-8250-75cf07f81bb8.png">
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/80724583/200448137-75b95550-7b9f-45dc-bde1-78964b8b4894.png">
It still says Headless is false after I enabled it; it ended with the same error by the way.

**Comment by dystoqia** [comment]
Ive freshly forked it before but ill try clearing the cache

**Comment by DerMuffin** [comment]
Its more like theres something wrong with your syntax. But i cant say what exactly it is.

Just to check:

- You fork that main repo
- Add a Secret "ACCOUNTS" to your repo
- Fill your Accounts in this secret like:

Account1@mail.com:Password Account2@mail.com:Password Account3@mail.com etc...

Mail and and password should be together, seperatet by double Point (:). You can add a new Account by leave a space between the Password of Account one and Mail from Account two.

- Dont edit the workflow file for Deploy process. Just check if the following parameters are set: --headless --privacy --fast
- Headless in mandatory for Github which used for Systems without GUI, privacy hide you Mail in the logs, fast let the script run faster.

I run many Accounts on here. Never had problems.

Check theese things. If the error persists, we may need to view it together via Teamviewer etc. (if you like)

**Comment by DerMuffin** [comment]
Can reproduce this issue.

Upload my script to replit.com where you only have a shell to execute this. Adding my Account. Same error.

Must be something related to Linux with only a shell.

Github Workflow should be working fine

**Comment by DerMuffin** [comment]
Create a pull request on your repo. Just pull it and tell me if it works for you!

**Comment by DerMuffin** [comment]
Issue will be closed. Fixed by using --headless and check for existance of Chrome on the system
