### ISSUE TITLE
clarifying readme warnings

### ISSUE THREAD

**Issue by mgrimace** [MehdiRtal/MicrosoftRewardsBot#33]
What does "Warning: don't use outlook" refer to in the readme? As in don't use an outlook-based MS account? Are they not by default outlook?

Thanks!

**Comment by gdrhzrd6e** [comment]
use third party email to sign up to outlook

**Comment by DerMuffin** [comment]
More like use a third party app to sign up into Microsoft Rewards. Dont use a outlook Mail with Rewards when you using multiple accounts

@mgrimace

**Comment by gdrhzrd6e** [comment]
signing up to ms rewards or signing up to outlook is same thing you just have to press the join button to enrol yourself n rewards program

**Comment by DerMuffin** [comment]
Issue can be closed. README is updated
