### ISSUE TITLE
what you mean with dont use outlook?

### ISSUE THREAD

**Issue by badplay** [MehdiRtal/MicrosoftRewardsBot#34]
I think i have to need a outlook login or isnt it ??

**Comment by DerMuffin** [comment]
Hey @badplay ,

you shouldnt use Outlook Mail Accounts. Like Username@outlook.com. They more likely to get banned when using multiple Accounts

**Comment by badplay** [comment]
but which one then ? when i reg on bing i can only choose outlook.com .de and hotmail.com

**Comment by DerMuffin** [comment]
You can use any Mail you want while register for MS Rewards.

When you are on this site: https://www.microsoft.com/en-us/rewards

Theres a button "Join Now". Click it.

Now it should ask you for an email. Type any mail you want (and have access to) in there. If no rewards account is registered under this mail it will ask you to create you a account with this Mail.

All you need to do is pick a password then.

@badplay

**Comment by DerMuffin** [comment]
Issue can be closed. README is updated

**Comment by gdrhzrd6e** [comment]
you can use any tempmail
https://generator.email

**Comment by badplay** [comment]
i used a tempmail after 2 days they closed my acc becorse of strange acitvitys :( what now? they want to send me an sms but i have no sim for fake

**Comment by badplay** [comment]
@DerMuffin 

hey can we write maybe with mail or something i see you speaking german. will be great to have one that can help a litte :)

**Comment by DerMuffin** [comment]
@badplay 

Hit me up on Discord: Der Muffin#4567

i will try to help you. Speaking german aswell.
