### ISSUE TITLE
executable package

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#39]
![image](https://user-images.githubusercontent.com/104626684/200976563-f6f633b6-a65e-4803-9397-b18f821ad9a7.png)
this error is a problem which randomwords

**Comment by DerMuffin** [comment]
When does this occured?

**Comment by MehdiRtal** [comment]
> ![image](https://user-images.githubusercontent.com/104626684/200976563-f6f633b6-a65e-4803-9397-b18f821ad9a7.png) this error is a problem which randomwords

Does it happen with pyinstaller ?

**Comment by gdrhzrd6e** [comment]
yeah but the error is fixed when you remove searchng or random words function

**Comment by gdrhzrd6e** [comment]
when i run the exe the error disappeared when i removedsearch/randomword

**Comment by MehdiRtal** [comment]
> when i run the exe the error disappeared when i removedsearch/randomword

I believe you should also bundle random_word\config.yml.gpg while packaging.

**Comment by MehdiRtal** [comment]
> > when i run the exe the error disappeared when i removedsearch/randomword
> 
> I believe you should also [bundle](https://pyinstaller.org/en/stable/usage.html#cmdoption-p) `random_word\config.yml.gpg` while packaging.

running `pyinstaller -F .\MicrosoftRewardsBot.py --collect-all random_word` fixes it.
