### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by matchqq** [MehdiRtal/MicrosoftRewardsBot#42]
Got this error when running python MicrosoftRewardsBot.py. Any help?

Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1211, in farmer
    browser = browserSetup(False, PC_USER_AGENT, random.choice(ARGS.proxies) if ARGS.proxies else None)
  File "MicrosoftRewardsBot.py", line 77, in browserSetup
    chrome_browser_obj = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1309, in <module>
    main()
  File "MicrosoftRewardsBot.py", line 1299, in main
    farmer()
  File "MicrosoftRewardsBot.py", line 1273, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

**Comment by gdrhzrd6e** [comment]
do you have chrome installed?

**Comment by matchqq** [comment]
Yes. Chrome driver too.

**Comment by DerMuffin** [comment]
Run --headless when in terminal session

**Comment by matchqq** [comment]
Same error:
PS C:\Bing> python MicrosoftRewardsBot.py --headless
[INFO] everyday : None
[INFO] headless : True
[INFO] session : False
[INFO] error : False
[INFO] fast : False
[INFO] accounts : None
[INFO] proxies : None
[INFO] privacy : False

[LOGS] Logs loaded successfully.

********************redacted@gmail.com********************

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 107.0.5304
[WDM] - Get LATEST chromedriver version for 107.0.5304 google-chrome
[WDM] - Driver [C:\Users\HP\.wdm\drivers\chromedriver\win32\107.0.5304.62\chromedriver.exe] found in cache


Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1211, in farmer
    browser = browserSetup(False, PC_USER_AGENT, random.choice(ARGS.proxies) if ARGS.proxies else None)
  File "MicrosoftRewardsBot.py", line 77, in browserSetup
    chrome_browser_obj = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1309, in <module>
    main()
  File "MicrosoftRewardsBot.py", line 1299, in main
    farmer()
  File "MicrosoftRewardsBot.py", line 1273, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

**Comment by MehdiRtal** [comment]
Are you running windows?

**Comment by matchqq** [comment]
yes.

**Comment by matchqq** [comment]
I'm using 3.6...

**Comment by DerMuffin** [comment]
Hmm okay. So Python is also alright then...

**Comment by matchqq** [comment]
I didn't add the new python to the environment... Doing it now.

**Comment by matchqq** [comment]
It's working now! Thank you everyone for chiming in.
I've been using the farmer version forever even though many functions there aren't working anymore. This is so awesome.

**Comment by DerMuffin** [comment]
What you mean with "many functions arent working"?

That something in this Script not work or in General other Scripts dont work anymore?

**Comment by matchqq** [comment]
I meant charlesbel's version which cannot to mobile searches, stuck in some activities, and does not continue to next account when first one is done. Yours have got all those working.

**Comment by DerMuffin** [comment]
Yeah we Maintan it. Hope you enjoy using it. Closing this Issum now.
