### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by Axel3026** [MehdiRtal/MicrosoftRewardsBot#45]
Does there have to be a rule that says if you use vpn or not? So when I use it and I'm in the United States and I want to move to Germany, I don't have to delete the log.txt. Thank you
---VPN True

**Comment by MehdiRtal** [comment]
Can you provide more information?

**Comment by Axel3026** [comment]
This is going to be complicated.
I use a vpn and I want that in this selection section:
![image](https://user-images.githubusercontent.com/87623383/202855453-ef05c407-6854-49e1-8f3a-fb95706a19d2.png)

an option appears that says VPN, since the program only works with one country and when I enter the other it tells me that I no longer have missions, so I have to delete the log.txt file to detect that I have new missions thanks to the other country .

that at the end of the app it asks you do you want to use any other country?
and you put yes, then what the program does is run it again. And there it begins to make Germany in my case. I manage the vpn manually, I don't want it to be automatic.

**Comment by DerMuffin** [comment]
@Axel3026 Have a look at this script:

https://github.com/Prem-ium/BingRewards

Theres a option which called "WANTED_IPV4". Its  claim your current IP Adress and compare it to the IP you write down for "WANTED_IPV4"

Maybe this is a option for you?

**Comment by Axel3026** [comment]
@DerMuffin  no, I didn't want that, I said some argument to load the script again without having to delete the log.txt manually since I was using a VPN and the information from the previous country remained and it did not detect that it was a new country with new missions. but it's not needed anymore, since I use ```Github Action```
