### ISSUE TITLE
Faster Daily Breakdown

### ISSUE THREAD

**Issue by Axel3026** [MehdiRtal/MicrosoftRewardsBot#51]
I think it can be done, I would like the breakdown to be much faster or that it can be disabled completely and so I do it manually or with a script that I have in tampermonkey, this is the code:

// ==UserScript==
// @name         Microsoft Rewards Bot
// @namespace    http://tampermonkey.net/
// @version      1.45
// @description  I will hack microsoft rewards for you!!! You can also do other stuff while it is running.
// @author       You
// @match        *://*/*
// @grant        none
// ==/UserScript==
(function() {

    'use strict';
    if (document.readyState == "complete" || document.readyState == "loaded" || document.readyState == "interactive") {
        clickCards()
    } else {

        document.addEventListener("DOMContentLoaded", function(event) {
            clickCards()
        });
    }
})();
function randomString(length) {
    var result = '';
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() *
 charactersLength));
   }
   return result;
}

function clickCards(){
    var first = true
    const params = new URLSearchParams(window.location.search)
    if (params.has('searchTab')){
        if (params.get('first') == "true"){
            localStorage.setItem('numSearch', 0);
        }
        var numSearch = localStorage.getItem('numSearch');
        if (numSearch === null){
            numSearch = 0
        }
        localStorage.setItem('numSearch', parseInt(numSearch) + 1);
        console.log(numSearch)
        if (numSearch >= 90){
            close();
        }
        document.location.href = "https://www.bing.com/search?searchTab=true&q=" + randomString(3);
    }
    if (window.location.href === "https://rewards.microsoft.com/"){
        window.open("https://www.bing.com/search?q=abc&searchTab=true&first=true", '_blank').focus();
    }
    if (params.has('rnoreward')){
        setInterval(function(){
            if (document.querySelector(".btOption.b_cards")){
                document.querySelector(".btOption.b_cards").click()
            }
            if (document.getElementById("rqStartQuiz")){
                document.getElementById("rqStartQuiz").click()
            }
            if (document.querySelector(".wk_choicesInstLink")){
                document.querySelector(".wk_choicesInstLink").click()
            }
            if (document.querySelector(".wk_button")){
                document.querySelector(".wk_button").click()
            }
            var largeAnswer = document.querySelectorAll(".b_cards")
            if (largeAnswer.length){

                for (let i = 0; i < largeAnswer.length; i++) {
                    if (largeAnswer[i].getAttribute("iscorrectoption") === "True"){
                        largeAnswer[i].click()
                    }
                }
            }

            var smallAnswer = document.querySelectorAll(".rqOption")
            if (smallAnswer.length) {
                for (let i = 0; i < smallAnswer.length; i++) {
                    smallAnswer[i].click()
                }
            }
        }, 600)

    }
    var plus10 = document.querySelectorAll(".mee-icon.mee-icon-AddMedium")
    if (plus10){
      var plus10Length = plus10.length

      for (let i = 0; i < plus10Length; i++) {
          console.log(plus10[i])
          plus10[i].parentNode.parentNode.parentNode.parentNode.click()
      }
    }

}

**Comment by DerMuffin** [comment]
Please create a pull request, if you have useful features to add. Thanks

**Comment by grant** [comment]
Please do not mention me @grant unless you request my attention.

**Comment by Axel3026** [comment]
@grant  I didn't want to mention you, sorry the code had that, it wasn't my intention

**Comment by grant** [comment]
> @grant  I didn't want to mention you, sorry the code had that, it wasn't my intention

> No worries. Using `code blocks` stops it in the future.
