### ISSUE TITLE
Question on multiple accounts. 

### ISSUE THREAD

**Issue by GioPresta** [MehdiRtal/MicrosoftRewardsBot#52]
When I redeem the rewards it asks me for a phone number, can I use the same number on multiple accounts or do I risk being banned?  How do you do it?

**Comment by gdrhzrd6e** [comment]
you can but best not to for same number more than 4 times every 24 hours otherwise they may ban you even if it goes through
i would just get all your accounts to 13k points then buy some cheap sims plans or go to phone boxes and redeem them

**Comment by gdrhzrd6e** [comment]
i have redeemed 14 accounts on same number before same day
so only do the above if its a huge amount of points

**Comment by GioPresta** [comment]
Thanks a lot for the answer. Will I try to be careful and maybe buy some numbers on https://sms-activate.org/ or risk being banned because they recognize them?

**Comment by DerMuffin** [comment]
Nah, i dont think so. Its more about using the same number and not which one
