### ISSUE TITLE
[ERROR] No internet connection.

### ISSUE THREAD

**Issue by kressety** [MehdiRtal/MicrosoftRewardsBot#57]
At GitHub Actions
```
[WDM] - Downloading:   0%|          | 0.00/7.[26](https://github.com/kressety/MicrosoftRewardsBot/actions/runs/3569876034/jobs/6000281357#step:6:27)M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 7.26M/7.26M [00:00<00:00, 161MB/s]
[LOGIN] Logging-in...
[LOGIN] Writing email...


[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
[ERROR] No internet connection.
```
Then it stuck for 20mins and retry at hundreds of times till I stop it manually.

**Comment by DerMuffin** [comment]
Sign into your account manually and check if you can login. Sometimes there are some weird windows, which this script cant handle

**Comment by kressety** [comment]
There's no problem when I log in on a device where I have never logged in. No two-factor validation or other window, just email account with password. 
So, I run Reward Bot on a Linux server, it'll fail sometimes when logging in but finally works as expected.
However, in GitHub actions it never works.

**Comment by DerMuffin** [comment]
Ah okay. Sometimes Github Actions act kinda weird. Have a similar thing with another Testaccount.

You can try to clear your cache or try it with another Github account. Just to be sure.

Didnt find a solution for me too

**Comment by kressety** [comment]
Got it, Thank you. 
As a temporary method I think there should be a limit to the running time of workflows to avoid billing when Bot gets stuck, and retry after workflows' break if possible.

**Comment by DerMuffin** [comment]
The Problem with the running time is a bit complicated. Because this Script runs on different hardware with different number of accounts.

For what i can tell, with Workflow a single Account take about 15 Minutes to complete.

**Comment by mgrimace** [comment]
> Got it, Thank you. 
> 
> As a temporary method I think there should be a limit to the running time of workflows to avoid billing when Bot gets stuck, and retry after workflows' break if possible. 

Agreed (if possible). I had the same issue running it on GitHub actions and it ran for 6-hours before erroring out. 

FYI mine resolved when I went to security in my MS email account and noticed that "authenticator" as a verification method had been re-enabled (either automatically or by MS). Disabling this seemed to resolve the error, though it could have been coincidental.

**Comment by kressety** [comment]
#60 
So I try to set a time limit. Terminating when the running time is out of 20mins and retry for one time.

**Comment by mgrimace** [comment]
My average run time with one account is around 23 mins, any chance you could extend the time to give a little room so it doesn't disrupt a "normal" run?

**Comment by kressety** [comment]
@mgrimace 
Maybe 40mins? 
I dont think it'll be longer, if running properly.

**Comment by MehdiRtal** [comment]
I changed it to 30mins, I think it will be enough.

**Comment by mgrimace** [comment]
> I changed it to 30mins, I think it will be enough.

That makes sense, thanks!

**Comment by kressety** [comment]
It may be better show 'Success' at workflow summary when the first try failed and the second try succeeded, but I dont know how to make it.

**Comment by MehdiRtal** [comment]
I believe you should catch the exception, I'll take a look at it later.
