### ISSUE TITLE
this may be password syntax

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#58]
Run python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
/home/runner/work/_temp/d4d97659-1355-4d89-873f-6f2e513[11](https://github.com/gdrhzrd6e/MicrosoftRewardsBot/actions/runs/3570924022/jobs/6002342150#step:6:12)cc8.sh: line 1: @o5/%,: No such file or directory
Error: Process completed with exit code 1.

**Comment by DerMuffin** [comment]
For me the script is running fine after the update. Where did this issue happend?

**Comment by Axel3026** [comment]
@gdrhzrd6e note that you wrote it correctly in secret, the same thing happened to me

**Comment by DerMuffin** [comment]
Issue closed because of missing information
