### ISSUE TITLE
[ERROR] Unusual activity detected !

### ISSUE THREAD

**Issue by FuryCraft** [MehdiRtal/MicrosoftRewardsBot#6]
When I use Github actions now it returns [ERROR] Unusual activity detected !

**Comment by MehdiRtal** [comment]
Can I see the workflow run?

**Comment by MehdiRtal** [comment]
You can also try to disable any security related features on your Microsoft account such as 2FA..

**Comment by FuryCraft** [comment]
![Uploading image.png…]()
And i don't have 2FA enabled

**Comment by FuryCraft** [comment]
I run the script on my computer and it works fine but on github actions there is this error

**Comment by MehdiRtal** [comment]
Yes because GitHub Actions runs on cloud and the location is probably different, so you probably should allow it on your Microsoft account security settings.

**Comment by MehdiRtal** [comment]
[Here](https://account.live.com/Activity) you can see all your account activities.
