### ISSUE TITLE
What do I have to put in goal?

### ISSUE THREAD

**Issue by Axel3026** [MehdiRtal/MicrosoftRewardsBot#62]
```
[
  {
    "username": "Your Email",
    "password": "Your Password",
    "mobile_user_agent": "Your Preferred Mobile User Agent",
    "goal": "Tarjeta regalo de League of Legends: 100 RP"
  },
]
```
Where do I get the name that I have to copy if I have it in Spanish?

![image](https://user-images.githubusercontent.com/87623383/204573038-dbc8df05-e256-42a6-bf34-c2f616ec486a.png)
![image](https://user-images.githubusercontent.com/87623383/204573840-a78e0c70-190c-4726-ab01-37cafeb4eddd.png)

**Comment by MehdiRtal** [comment]
@dmarts05

**Comment by dmarts05** [comment]
> ```
> [
>   {
>     "username": "Your Email",
>     "password": "Your Password",
>     "mobile_user_agent": "Your Preferred Mobile User Agent",
>     "goal": "Tarjeta regalo de League of Legends: 100 RP"
>   },
> ]
> ```
> 
> Where do I get the name that I have to copy if I have it in Spanish?
> 
> ![image](https://user-images.githubusercontent.com/87623383/204573038-dbc8df05-e256-42a6-bf34-c2f616ec486a.png) ![image](https://user-images.githubusercontent.com/87623383/204573840-a78e0c70-190c-4726-ab01-37cafeb4eddd.png)

Hi, the script as of now only supports the first available reward (100RP) and not higher value rewards. You should write in "goal" the following: 

```
json
"goal":  "Tarjeta regalo de League of Legends"
```

**Comment by Axel3026** [comment]
@dmarts05 Thank you very much for the help
