### ISSUE TITLE
Github Actions doesn't actually complete tasks and quests

### ISSUE THREAD

**Issue by haobinliang** [MehdiRtal/MicrosoftRewardsBot#79]
Hi,

I've set up the Github Actions correctly and the deployment was successful. Looking at the log, it did log into my account and did the work; however, none of the points was actually collected.

Here's the `Run script` part of the log for the deployment (https://github.com/haobinliang/MicrosoftRewardsBot/actions/runs/3635059816/jobs/6133801379). It's the start of the day so no point was completed at all. Any idea what may cause this please?

(Just a note, all points can be collected correctly if I run it locally on my Mac; just not working for Github Actions).

```
Run timeout 1800 python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
[INFO] everyday : None

[INFO] headless : True
[INFO] session : False
[INFO] error : False
[INFO] fast : True
[INFO] privacy : True
[INFO] emailalerts : False
[INFO] redeem : False

[LOGS] "logs.txt" file not found.
[LOGS] "logs.txt" created.

********************myusername@outlook.com********************
[WDM] - Downloading:   0%|          | 0.00/7.26M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 7.26M/7.26M [00:00<00:00, 82.7MB/s]
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 92087 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/30
[BING] 2/30
[BING] 3/30
[BING] 4/30
[BING] 5/30
[BING] 6/30
[BING] 7/30
[BING] 8/30
[BING] 9/30
[BING] 10/30
[BING] 11/30
[BING] 12/30
[BING] 13/30
[BING] 14/30
[BING] 15/30
[BING] 16/30
[BING] 17/30
[BING] 18/30
[BING] 19/30
[BING] 20/30
[BING] 21/30
[BING] 22/30
[BING] 23/30
[BING] 24/30
[BING] 25/30
[BING] 26/30
[BING] 27/30
[BING] 28/30
[BING] 29/30
[BING] 30/30
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 92087 points !

The script took : 00:24:10
```

**Comment by DerMuffin** [comment]
That might be just a display issue. If you are outside the US and you gonna login on your local Rewards Site you cant see the points that where collected by github.

Connect to a US VPN/Proxy and you will see that everything is right!

**Comment by DerMuffin** [comment]
Correct. Github Servers are US based. So they use the US Rewards. You cant choose directly from which Region you farm the points. If you want to collect the UK points, you need to add a UK-based proxy.

But its extremly difficult to find a proxy that works with rewards

**Comment by DerMuffin** [comment]
I' ve read that residential proxys work perfectly. But they really expensive.

**Comment by dmarts05** [comment]
> I' ve read that residential proxys work perfectly. But they really expensive.

I've been doing my own research and I have found that you can buy 1 residential proxy for 5$ a month which seems a fair price to me if you're going to get 30$ in Amazon Gift Cards for example each month with 6 accounts.

**Comment by DerMuffin** [comment]
> > I' ve read that residential proxys work perfectly. But they really expensive.
> 
> I've been doing my own research and I have found that you can buy 1 residential proxy for 5$ a month which seems a fair price to me if you're going to get 30$ in Amazon Gift Cards for example each month with 6 accounts.

Sure. Go ahead and try your luck! ;)

**Comment by haobinliang** [comment]
Thank you very much @DerMuffin @dmarts05 !!n

I guess I will just run it locally with cron just to save the trouble 🥲
