### ISSUE TITLE
add zyte

### ISSUE THREAD

**Issue by gdrhzrd6e** [MehdiRtal/MicrosoftRewardsBot#82]
https://docs.zyte.com/smart-proxy-manager/integrations/selenium.html#spm-selenium-integration

**Comment by DerMuffin** [comment]
Interesting. They also offers resedential proxys and auto rotate if a proxy doesnt have access to a site.

Only downside: Cost 30$ and resedential proxys not even included.

Think its not worth it until you have a really big amount of accounts

https://www.zyte.com/pricing/
