### ISSUE TITLE
What does this mean? 

### ISSUE THREAD

**Issue by badplay** [MehdiRtal/MicrosoftRewardsBot#85]
If you are using Github Actions then split accounts across multiple repositories/forks or use proxies.

I am new at github. What does this mean?

**Comment by Axel3026** [comment]
I think it refers to creating multi secret repositories,
example:
deploy1: two accounts
deploy2: other two or more accounts but don't go over 6

**Comment by DerMuffin** [comment]
Yes. You should use only 6 rewards Accounts per Repository

**Comment by badplay** [comment]
Does this alsow need when i put it on local directory only use max 6 accounts?
Can i use the bot on github without having a computer?

**Comment by Axel3026** [comment]
@badplay It is recommended that you use 6 accounts. and from my personal experience I use like 10 accounts on the same PC and for the moment nothing happened.
and if you can use github action so you don't use a computer since github provides you with an ip for each repository, I think so
